postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: delivery
  poolSize: 1000
auth:
  secretKey: "fchg678q314fgia7uywe7rfg798i4q"
otel:
  grpc_endpoint: otel-collector:4317
app:
  grpc_port: 50052